name: Greg Johnson
favicon: null
layout_spectrum: 0
typography_spectrum: 0.39231268921867013
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.5237273799721152
  lightness: 0.6118082839529961
  saturation: 0.9187753056176007
  rhythmicContrast: 0.4509052103385329
purpose: []
