name: Greg Johnson
favicon: null
layout_spectrum: 0.56455
typography_spectrum: 0.63599
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#78685a'
    - '#06379b'
    - '#fdd7ae'
    - '#a4ac96'
  brandStrength: 0.3125
  lightness: 0.6875
  saturation: 0.25
  rhythmicContrast: 0.8006067757960409
purpose: []
