name: Greg Johnson
favicon: null
layout_spectrum: 0.3976430054754019
typography_spectrum: 0.5088296630419791
title: Greg Johnson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#78685a'
    - '#06379b'
    - '#fdd7ae'
    - '#a4ac96'
  brandStrength: 0.3125
  lightness: 0.47576982667669654
  saturation: 0.1875
  rhythmicContrast: 0.8006067757960409
purpose: []
