layout_spectrum: 0.23683557799085975
typography_spectrum: 0.34273951477371156
color:
  brandColors:
    - '#962D3E'
    - '#343642'
    - '#979C9C'
    - '#F2EBC7'
    - '#348899'
  brandStrength: 0.12123414175584912
  lightness: 0.9573905963916332
  saturation: 0.6344557015690953
  rhythmicContrast: 0.31017613084986806
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-78770793-1
  facebook: null
  twitter: null
author:
  name: Greg Johnson
  email: g.johnson@oxfordalumni.org
  url: greg.buzz
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b258f910-47bb-4a15-a570-3339325be473.png
name: Greg Johnson
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c125dac9-f053-4ff8-8493-6e2c1087aa58.ico
title: ''
description: ''
purpose: []
