typography_spectrum: 0.5853061021771282
color:
  brandColors:
    - '#962D3E'
    - '#343642'
    - '#979C9C'
    - '#F2EBC7'
    - '#348899'
  brandStrength: 0.12123414175584912
  lightness: 0.9573905963916332
  saturation: 0.6344557015690953
  rhythmicContrast: 0.31017613084986806
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7087991300504655
analytics:
  google: UA-78770793-1
  facebook: null
  twitter: null
author:
  name: Greg Johnson
  email: ''
  url: greg.buzz
name: Greg Johnson
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: LinkedIn
    url: 'https://www.linkedin.com/in/greginternet'
    type: external
  - name: Facebook
    url: 'https://www.facebook.com/greg.johnson1'
    type: external
  - name: Twitter
    url: 'https://twitter.com/greg_oii'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c125dac9-f053-4ff8-8493-6e2c1087aa58.ico
title: ''
description: |+

purpose: []
