name: Greg Johnson
favicon: null
layout_spectrum: 0.7087991300504655
typography_spectrum: 0.39231268921867013
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.5858613892924041
  lightness: 0.2779305442236364
  saturation: 0.12340205581858754
  rhythmicContrast: 0.9392926173750311
purpose: []
