name: Greg Johnson
favicon: null
layout_spectrum: 0.3976430054754019
typography_spectrum: 0.5088296630419791
title: Greg Johnson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#020204'
    - '#a5b5be'
    - '#1aa2d3'
    - '#293b42'
  brandStrength: 0.3125
  lightness: 0.47576982667669654
  saturation: 0.25
  rhythmicContrast: 0.8006067757960409
purpose: []
