name: Greg Johnson
favicon: null
layout_spectrum: 0.78997
typography_spectrum: 0.49341
title: Greg Johnson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a51b34'
    - '#d14b63'
    - '#fe7e96'
    - '#feb24e'
  brandStrength: 0.3125
  lightness: 0.6875
  saturation: 0.25
  rhythmicContrast: 0.8006067757960409
purpose: []
