name: Greg Johnson
favicon: null
layout_spectrum: 0.86704
typography_spectrum: 0.49341
title: Greg Johnson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfdde'
    - '#320b37'
    - '#e5ce9a'
    - '#cb3977'
    - '#996464'
  brandStrength: 0.3125
  lightness: 0.6875
  saturation: 0.25
  rhythmicContrast: 0.8006067757960409
purpose: []
