name: Greg Johnson
favicon: null
layout_spectrum: 0.3976430054754019
typography_spectrum: 0.5088296630419791
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.12642722227610648
  lightness: 0.47576982667669654
  saturation: 0.15062056574970484
  rhythmicContrast: 0.8006067757960409
purpose: []
