typography_spectrum: 0.39231268921867013
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.5858613892924041
  lightness: 0.2779305442236364
  saturation: 0.12340205581858754
  rhythmicContrast: 0.9392926173750311
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7087991300504655
analytics:
  google: null
  facebook: null
  twitter: null
name: Greg Johnson
cta:
  domain: null
  bucket: null
  version: null
favicon: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/c125dac9-f053-4ff8-8493-6e2c1087aa58.ico'
title: null
purpose: []
