name: Greg Johnson
favicon: null
layout_spectrum: 0.7362
typography_spectrum: 0.63599
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b53e1b'
    - '#3677b2'
    - '#e3b6a9'
    - '#d08670'
  brandStrength: 0.3125
  lightness: 0.6875
  saturation: 0.25
  rhythmicContrast: 0.8006067757960409
purpose: []
