name: Greg Johnson
favicon: null
layout_spectrum: 0
typography_spectrum: 0.63599
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#55b581'
    - '#88c056'
    - '#09a5c1'
    - '#bce5e0'
  brandStrength: 0.6875
  lightness: 0.8125
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
